name: dartlang_china
version: 0.0.1
author: Jaron Tai <jaroncn@gmail.com>
description: The dartlang-china.org site.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  redstone: any
  shelf_static: any
dev_dependencies:
  unittest: any
